apiVersion: v1
kind: ResourceQuota
metadata:
  name: nagp-resource-quota
  namespace: nagp
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    services.loadbalancers: "1"
